### ISSUE TITLE
Does it work with go 1.11 modules

### ISSUE THREAD

**Issue by Vad1mo** [getgauge-contrib/gauge-go#18]
I am trying to make the runner work with go 1.11 modules. Especially if the project is outside of the GOPATH. So I am wondering is this possible or does the plugin need adaption?

**Comment by sriv** [comment]
I dont believe gauge-go supports modules (yet). So this will need enhancement.

**Comment by Vad1mo** [comment]
yes, it doesn't work it assumes GOPATH to be mandatory. There need to be an modification to support 1.11 module concept.

**Comment by jorygeerts** [comment]
I did some quick testing and simply removing the `!checkIfInSrcPath(projectRoot)` check from `setPluginAndProjectRoots()` is enough to make things work (assuming the tests are in a project that uses Go Modules) outside of the GOPATH.

Having a check that ensures the tests can actually be ran makes sense, so I assume "delete the check" isn't an option. Perhaps that check can be altered to require either being inside the GOPATH or having Modules enabled (meaning: "have `go.mod` in some parent directory")? Maybe there could even be an option (can options be passed from `gauge init ...` into the plugin?) to instantiate go modules?

If such a change is welcome, I'm more than willing to write the code and submit a PR.

**Comment by BugDiver** [comment]
@jorygeerts Thanks for all your efforts. It would be really great if you can create a PR with the fix. We would happy to validate your PR.

> Maybe there could even be an option (can options be passed from gauge init ... into the plugin?) 

Currently there is no way to pass option to `gauge init ...` command. But as far as I know, the `go modules` are not enabled by default, they need to enable via `GO11MODULE` env. I guess the `gauge init go` can piggyback on the same end, and generate the files accordingly.

**Comment by jorygeerts** [comment]
I have basic Modules support working.
During `gauge init go`, the process is:

1. Are we in GOPATH? Yes -> OK
1. Is Modules supported (technically: is this Go 1.11+)? No -> Tell the user we need to either be on the GOPATH or have Go 1.11+
1. Is there a `go.mod` in this directory, or one of its parents (recursively)*? Yes -> OK
1. Try `go mod init`. Did that work? Yes -> OK
1. Tell the user to run `go mod init <module-name>`

*: This recursion is here to make things work in a situation where the gauge tests are in a subdirectory of a repository contains a Golang application. I don't know if that is a typical use case, but it is how we use Gauge here.

What `go mod init` does to guess the module name is (in this order) look for GoDep files, vendor files, check if the project is on the GOPATH, check if git is used with GitHub as remote. If all of those fail, `go.mod` cannot be created (leading to point 5 - tell them user to do it themselves).

When the runner is started, steps 1 trough 3 are done. If things aren't OK, the user is told again to run `go mod init <module-name>` themselves; then we exit.

From what I understand a check on `GO111MODULE` isn't needed here, because that is only used to enable Modules support inside the GOPATH; if we're in the GOPATH it doesn't matter for the runner if Modules is enabled or not, it will work either way.

My changes cover the use case I have. @Vad1mo if you have any additional requirements outside of "run outside of GOPATH" I can try and implement those as well. Otherwise I'll submit my PR as-is.

**Comment by jorygeerts** [comment]
I've just created PR #19 which has the changes needed to work outside of $GOPATH by using Go Modules.

I know this solved the use case I have; based on the issue I think it also solves @Vad1mo his issue.

**Comment by Vad1mo** [comment]
I'll give it a try again and see if the PR works

**Comment by Vad1mo** [comment]
thank you @jorygeerts 👏

**Comment by jorygeerts** [comment]
Great @Vad1mo! Let me know how things work for you. :)

**Comment by jorygeerts** [comment]
@BugDiver When you have the time, can you take a look at #19 ?

**Comment by x80486** [comment]
@jorygeerts, I know this is closed, but it currently doesn't work for me.

```shell
[x80486@uplink gauge-basics]$ pwd
/home/x80486/Workshop/Development/gauge-basics/

[x80486@uplink gauge-basics]$ go version
go version go1.12.6 linux/amd64

[x80486@uplink gauge-basics]$ echo $GOPATH
/home/x80486/Workshop/Development/go

[x80486@uplink gauge-basics]$ gauge init go
Project folder must be a subfolder in GOPATH/src folder
Error ----------------------------------

Failed to initialize project. exit status 1

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://gitter.im/getgauge/chat

Your Environment Information -----------
	linux, 1.0.5, 562f036
	go (0.1.2), html-report (4.0.8), java (0.7.2), screenshot (0.0.1)
```

It doesn't matter if there is already a `go.mod` file or not; I tried with an empty project, and also with (a not-so-empty) project containing only a `go.mod` file (created via `go mod init gitlab.com/x80486/gauge-basics`)...but still, I always get the same error message: `Project folder must be a subfolder in GOPATH/src folder ...`.

**Comment by jorygeerts** [comment]
Yes, it because there hasn't been a release yet.
On the machines where I need these changes, I just followed the "build from source" steps in the readme to build and install the plugin based on the latest master.

Based on https://github.com/getgauge-contrib/gauge-go/compare/v0.1.2...master there are actually quite a few changes that haven't been released yet (though some of them are from before the last release, I'm not sure what's going on there).

@nehashri do you know if there are plans for a new release?

**Comment by nehashri** [comment]
@jorygeerts We will look at releasing it soon.

**Comment by BugDiver** [comment]
@x80486  The go plugin v0.1.3 has been released.

**Comment by x80486** [comment]
...and I'm just testing it as "we speak" :sunglasses:

Thanks!
